services:
  qbittorrentvpn:
    container_name: qbittorrent-vpn
    image: binhex/arch-qbittorrentvpn:latest
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_CLIENT=wireguard
      - VPN_USER=${PROTONVPN_USERNAME}
      - VPN_PASS=${PROTONVPN_PASSWORD}
      - VPN_PROV=protonvpn
      - STRICT_PORT_FORWARD=no
      - LAN_NETWORK=${LAN_NETWORK}
      - WEBUI_PORT=8080
    networks:
      - proxy-net
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SSD_PATH}/qbittorrent:/config:rw
      - ${HDD_PATH}/htpc/downloads:/downloads:rw

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${SSD_PATH}/jellyfin:/config
      - ${HDD_PATH}/htpc/media:/media
      - ${HDD_PATH}/photos:/photos
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    ports:
      - "8096:8096"  # Web UI
      - "8920:8920"  # HTTPS
      - "1900:1900/udp"  # DLNA
      - "7359:7359/udp"  # Client discovery
    restart: unless-stopped
    networks:
      - proxy-net
      - default
    runtime: nvidia

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/prowlarr:/config
    restart: unless-stopped
    networks:
      - proxy-net

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/sonarr:/config
      - ${HDD_PATH}/htpc/media:/media
      - ${HDD_PATH}/htpc/downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy-net

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/radarr:/config
      - ${HDD_PATH}/htpc/media:/media
      - ${HDD_PATH}/htpc/downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy-net

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/overseerr:/config
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
