services:
  qbittorrentvpn:
    container_name: qbittorrent-vpn
    image: binhex/arch-qbittorrentvpn:latest
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8118:8118
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_CLIENT=wireguard
      - VPN_USER=${PROTONVPN_USERNAME}
      - VPN_PASS=${PROTONVPN_PASSWORD}
      - VPN_PROV=protonvpn
      - STRICT_PORT_FORWARD=no
      - LAN_NETWORK=${LAN_NETWORK}
      - WEBUI_PORT=8080
    networks:
    - proxy-net
    - default
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${SSD_PATH}/qbittorrent/config:/config:rw
    - ${HDD_PATH}/downloads:/downloads:rw

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
      - VERSION=docker
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}

    volumes:
      - ${SSD_PATH}/plex/config:/config
      - ${HDD_PATH}/media:/media
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    restart: unless-stopped
    networks:
      - proxy-net
      - default

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - proxy-net
      - default

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/sonarr/config:/config
      - ${HDD_PATH}/media:/media
      - ${HDD_PATH}/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - proxy-net
      - default

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/radarr/config:/config
      - ${HDD_PATH}/media:/media
      - ${HDD_PATH}/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - proxy-net
      - default

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SSD_PATH}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - proxy-net
      - default

networks:
  proxy-net:
    external: true
