services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    environment:
#      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN} # Only enable to create first user
      - SIGNUPS_ALLOWED=false # Disable public signups
      - DOMAIN=${VAULTWARDEN_DOMAIN}
    networks:
      - proxy-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy-net:
    external: true
