services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 6931:8080
    volumes:
      - ./filebrowser/data:/data
      - ./filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - proxy-net
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy-net:
    external: true
