services:
  # drive.ruurd.dev
  filebrowser-ruurd:
    container_name: filebrowser-ruurd
    image: gtstef/filebrowser:stable
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${HDD_PATH}/drive/ruurd:/srv
      - ${SSD_PATH}/filebrowser-ruurd:/home/filebrowser/data
    networks:
      - proxy-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # drive.bramercampers.nl
  filebrowser-bramer:
    container_name: filebrowser-bramer
    image: gtstef/filebrowser:stable
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${HDD_PATH}/drive/bramer:/srv
      - ${SSD_PATH}/filebrowser-bramer:/home/filebrowser/data
    networks:
      - proxy-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy-net:
    external: true