services:
  # drive.ruurd.dev
  filebrowser-ruurd:
    container_name: filebrowser-ruurd
    image: gtstef/filebrowser:stable
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${HDD_PATH}/drive/ruurd:/srv
      - ${SSD_PATH}/filebrowser-ruurd/database.db:/database.db
      - ${SSD_PATH}/filebrowser-ruurd/config.json:/config/settings.json
    networks:
      - proxy-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # drive.bramercampers.nl
  filebrowser-bramer:
    container_name: filebrowser-bramer
    image: gtstef/filebrowser:stable
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${HDD_PATH}/drive/bramer:/srv
      - ${SSD_PATH}/filebrowser-bramer/database.db:/database.db
      - ${SSD_PATH}/filebrowser-bramer/config.json:/config/settings.json
    networks:
      - proxy-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy-net:
    external: true